# Generated by Django 5.0.2 on 2025-08-16 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_logs', '0003_songlog_album_art_url_songlog_duration_ms_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='songlog',
            unique_together=set(),
        ),
    ]
