# Generated by Django 5.0.2 on 2025-05-31 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music_logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compared_song_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compared_ratings', to='music_logs.songlog')),
                ('song_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='music_logs.songlog')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
